markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 菲同凡响
host: yourdomain.com
desc: 记录一些点点滴滴

custom:
    category:
        linux: linux 
        php: php 
        git: git 
        vim: vim 
    categories:
      - name:  linux
        title: Linux 

      - name:  php
        title: PHP
      - name:  git
        title: git 
      - name:  vim
        title: vim 

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 郝中智
        email: wecangonow@sina.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wecangonow@sina.com
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
