markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 水滴石穿
host: yourdomain.com
desc: 日积月累.

custom:
    category:
        php: php
        vim: vim
        linux: linux
        git: git
    categories:
      - name:  php
        title: php
      - name:  vim
        title: vim
      - name:  linux
        title: linux
      - name:  git
        title: git

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Haozhongzhi
        email: wecangonow@sina.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wecangonow@sina.com
        gravatar: 205e460b479e2e5b48aec07710c08d50

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
