markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 水滴石穿
host: wecangonow.github.io
desc: 日积月累.

custom:
    category:
        c: 
        php: php
        vim: vim
        linux: linux
        git: git
        mysql: mysql
        datastructure: data structure
        designpattern: design pattern 
        ror: Ruby on Rails
    categories:
      - name:  c
        title: c language
      - name:  php
        title: php

      - name:  vim
        title: vim

      - name:  linux
        title: linux

      - name:  git
        title: git

      - name:  mysql
        title: mysql

      - name:  datastructure
        title: data structure

      - name:  designpattern
        title: design pattern
      - name:  ror
        title: Ruby on Rails 
    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 郝中智
        email: wecangonow@sina.com
        disqus: woaihzz
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wecangonow@sina.com
        gravatar: d5dab90bf93624a45fc5090594fa8d8X?s=80

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
